name: Mirror Netlify Site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'          # 03 UTC diario

permissions:
  contents: write                # permite push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout completo
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      # Descarga Netlify → docs/
      - name: Mirror site
        run: |
          rm -rf docs tmp-mirror
          mkdir -p docs tmp-mirror

          wget --mirror --convert-links --adjust-extension \
               --page-requisites --no-parent \
               -P tmp-mirror \
               https://generador-crm-hma-kdj-github.netlify.app/

          rsync -a tmp-mirror/generador-crm-hma-kdj-github.netlify.app/ docs/

          # 1. Insertar <base>
          find docs -name "index.html" -print0 | while IFS= read -r -d '' f; do
            sed -i '0,/<head>/s//<head><base href="\/generador-crm-static\/">/' "$f"
          done

          # 2. Convertir fetch('/menu.html') y fetch('/footer.html') → relativos
          find docs -name "*.html" -print0 | xargs -0 sed -i \
            -e "s|fetch('/menu.html'|fetch('menu.html'|g" \
            -e "s|fetch('/footer.html'|fetch('footer.html'|g"

          touch docs/.nojekyll
          rm -rf tmp-mirror

      # Commit + push (force-with-lease)
      - name: Commit & push
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Auto-update $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || true
          git push --force-with-lease origin main
