name: Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Mirror site
        run: |
          rm -rf docs tmp && mkdir -p docs tmp
          wget -q --mirror --convert-links --adjust-extension \
               --page-requisites --no-parent \
               -P tmp \
               https://generador-crm-hma-kdj-github.netlify.app/
          rsync -a tmp/generador-crm-hma-kdj-github.netlify.app/ docs/
          # <base>
          sed -i '0,/<head>/s//<head><base href="\/generador-crm-static\/">/' docs/index.html
          # fetch rutas relativas
          sed -i "s|fetch('/|fetch('|g" docs/*.html
          touch docs/.nojekyll
          rm -rf tmp
          
       - name: Commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  github-actions
          git config user.email github-actions@github.com

          # Traer posibles commits nuevos y re-aplicar el nuestro
          git pull --rebase --autostash origin main

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push origin main
          fi
