name: Mirror Netlify Site

on:
  workflow_dispatch:          # puedes lanzarlo manualmente
  schedule:
    - cron: '0 3 * * *'       # cada día a las 03:00 UTC

permissions:
  contents: write             # token con permiso de push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 0️⃣  Clona el repo con historial completo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 1️⃣  Descarga la web y la deja en docs/
      - name: Mirror site
        run: |
          rm -rf docs tmp-mirror
          mkdir -p docs tmp-mirror

          wget --mirror --convert-links --adjust-extension \
               --page-requisites --no-parent \
               -P tmp-mirror \
               https://generador-crm-hma-kdj-github.netlify.app/

          rsync -a tmp-mirror/generador-crm-hma-kdj-github.netlify.app/ docs/
          touch docs/.nojekyll          # Desactiva Jekyll en GitHub Pages
          rm -rf tmp-mirror

      # 2️⃣  Commit y push (forzado con lease para evitar "fetch first")
      - name: Commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit
