name: Mirror Netlify Site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror site
        run: |
          rm -rf docs tmp-mirror
          mkdir -p docs tmp-mirror

          wget --mirror --convert-links --adjust-extension \
               --page-requisites --no-parent \
               -P tmp-mirror \
               https://generador-crm-hma-kdj-github.netlify.app/

          rsync -a tmp-mirror/generador-crm-hma-kdj-github.netlify.app/ docs/

          # insertar etiqueta <base>
          find docs -name "index.html" -print0 | while IFS= read -r -d '' f; do
            sed -i '0,/<head>/s//<head><base href="\/generador-crm-static\/">/' "$f"
          done

          touch docs/.nojekyll
          rm -rf tmp-mirror

      - name: Commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add -A
          git commit -m "Auto-update $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || true
          git push --force-with-lease origin main
