name: Mirror Netlify Site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'       # 03 UTC cada día

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      #   Checkout completo
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      #   Descargar sitio en docs/
      - name: Mirror site
        run: |
          rm -rf docs tmp-mirror
          mkdir -p docs tmp-mirror

          wget --mirror --convert-links --adjust-extension \
               --page-requisites --no-parent \
               -P tmp-mirror \
               https://generador-crm-hma-kdj-github.netlify.app/

          rsync -a tmp-mirror/generador-crm-hma-kdj-github.netlify.app/ docs/
          touch docs/.nojekyll
          rm -rf tmp-mirror

      #   Commit & push con rebase + force-with-lease
      - name: Commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"

          # integrar posible avance remoto
          git pull --rebase --autostash origin main

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push --force-with-lease origin main
          fi
