name: Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror site
        run: |
          rm -rf docs tmp
          mkdir -p docs tmp

          wget -q --mirror --convert-links --adjust-extension \
               --page-requisites --no-parent \
               -P tmp \
               https://generador-crm-hma-kdj-github.netlify.app/

          rsync -a tmp/generador-crm-hma-kdj-github.netlify.app/ docs/

          # Insertar etiqueta <base>
          sed -i '0,/<head>/s//<head><base href="\/generador-crm-static\/">/' docs/index.html

          # Convertir rutas absolutas en fetch()
          find docs -name "*.html" -print0 | xargs -0 sed -i \
            -e "s|fetch('/menu.html'|fetch('menu.html'|g" \
            -e "s|fetch('/footer.html'|fetch('footer.html'|g"

          touch docs/.nojekyll
          rm -rf tmp

      - name: Commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add -A
          git commit -m "Auto-update $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || true
          git push --force-with-lease origin main
