name: Mirror Netlify Site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'        # cada día 03 UTC

permissions:
  contents: write              # necesario para push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #  Checkout completo
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      #   Descarga y prepara en docs/
      - name: Mirror site
        run: |
          rm -rf docs tmp-mirror
          mkdir -p docs tmp-mirror

          wget --mirror --convert-links --adjust-extension \
               --page-requisites --no-parent \
               -P tmp-mirror \
               https://generador-crm-hma-kdj-github.netlify.app/

          rsync -a tmp-mirror/generador-crm-hma-kdj-github.netlify.app/ docs/

          # ---- Inserta <base href="/generador-crm-static/"> en cada index.html ----
          find docs -name "index.html" -print0 | while IFS= read -r -d '' f; do
            sed -i '0,/<head>/s//<head><base href="\/generador-crm-static\/">/' "$f"
          done

          touch docs/.nojekyll           # desactiva Jekyll
          rm -rf tmp-mirror

      #   Commit + push (rebase + force-with-lease)
      - name: Commit & push
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"

          git pull --rebase --autostash origin main

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push --force-with-lease origin main
          fi
