name: Mirror Netlify Site

on:
  workflow_dispatch:          # lo puedes lanzar a mano
  schedule:
    - cron: '0 3 * * *'       # cada noche a las 03:00 UTC

permissions:
  contents: write             # token con permiso de push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 1️⃣ Descargar la web y colocarla en docs/
      - name: Mirror site
        run: |
          # Limpiar destino
          rm -rf docs
          mkdir -p docs

          # Descargar sitio a temporal
          rm -rf tmp-mirror
          mkdir tmp-mirror

          wget --mirror --convert-links --adjust-extension \
               --page-requisites --no-parent \
               -P tmp-mirror \
               https://generador-crm-hma-kdj-github.netlify.app/

          # Copiar contenido final a docs/
          rsync -a tmp-mirror/generador-crm-hma-kdj-github.netlify.app/ docs/

          # Borrar temporal
          rm -rf tmp-mirror

      # 2️⃣ Commit & push (si hay cambios)
           - name: Commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"

          # Trae los cambios que haya en la rama remota
          git pull --rebase --autostash origin main

          # Añade los nuevos ficheros descargados
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            git push origin main
          fi

